default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { "5432" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "osp_app" } %>
  prepared_statements: <%= ENV.fetch("DATABASE_PREPARED_STATEMENTS") { true } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV.fetch("DATABASE_NAME") { "osp_app_test" }}#{ENV['TEST_ENV_NUMBER']}" %>

production:
  <<: *default
