# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en

## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
    - app
    - lib

  # Root directories for relative keys resolution.
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/services
    - app/views
    - app/cells

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - "*.jpeg"
    - "*.odt"
    - "*.docx"

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  strict: false

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

translation:
  deepl_api_key: <%= ENV["DEEPL_API_KEY"] %>

# Do not consider these keys missing:
ignore_missing:
 - faker.*
 - decidim.devise.shared.omniauth_buttons.or
 - devise.shared.links.sign_in_with_provider
 - layouts.decidim.header.user_menu
 - decidim.statutory_representative.inform.{subject,body}
 - decidim.devise.registrations.new.*
 - devise.failure.invited
 - devise.registrations.new.sign_up
 - layouts.decidim.social_media_links.*
 - decidim.proposals.create.*
 - decidim.proposals.proposals.compare.no_similars_found
 - decidim.proposals.publish.*
 - decidim.proposals.update_draft.*
 - decidim.proposals.destroy_draft.*
 - decidim.proposals.update.*
 - decidim.proposals.withdraw.errors.has_supports
 - decidim.verifications.sms.authorizations.edit.*
 - decidim.accessibility.skip_button
 - decidim.admin.participatory_space_private_users.create.*
 - decidim.meetings.directory.meetings.index.all
 - decidim.meetings.meeting.not_allowed
 - decidim.meetings.meetings.error
 - decidim.meetings.meetings.new.*
 - decidim.meetings.meetings.success
 - decidim.meetings.participatory_process_publications.create.*
 - decidim.meetings.participatory_process_publications.destroy.*
 - decidim.meetings.participatory_process_step_activations.create.*
 - decidim.meetings.participatory_process_steps.create.*
 - decidim.meetings.participatory_process_steps.default_title
 - decidim.meetings.participatory_process_steps.destroy.*
 - decidim.meetings.participatory_process_steps.edit.*
 - decidim.meetings.participatory_process_steps.index.steps_title
 - decidim.meetings.participatory_process_steps.new.*
 - decidim.meetings.participatory_process_steps.ordering.error
 - decidim.meetings.participatory_process_steps.update.error
 - decidim.meetings.participatory_process_steps.update.success
 - decidim.meetings.participatory_process_user_roles.*
 - decidim.meetings.participatory_processes.create.*
 - decidim.meetings.participatory_processes.edit.update
 - decidim.meetings.participatory_processes.index.*
 - decidim.meetings.participatory_processes.new.*
 - decidim.meetings.participatory_processes.update.*
 - decidim.meetings.participatory_processes_copies.create.error
 - decidim.meetings.participatory_processes_copies.create.success
 - decidim.meetings.participatory_processes_group.create.error
 - decidim.meetings.participatory_processes_group.create.success
 - decidim.meetings.titles.participatory_process_groups
 - decidim.meetings.titles.participatory_processes
 - decidim.meetings.users.resend_invitation.error
 - decidim.meetings.users.resend_invitation.success
 - decidim.verifications.sms.authorizations.new.{title,send}

# Consider these keys used:
ignore_unused:
  - faker.*
  - activemodel.attributes.osp_authorization_handler.*
  - activemodel.attributes.participatory_process.private_space
  - decidim.amendments.emendation.announcement.evaluating
  - decidim.authorization_handlers.osp_authorization_handler.{explanation, name}
  - decidim.authorization_handlers.osp_authorization_handler.fields.*
  - decidim.authorization_handlers.osp_authorization_workflow.name
  - decidim.events.budgets.pending_order.*
  - decidim.events.users.user_officialized.*
  - decidim.events.verifications.verify_with_managed_user.*
  - decidim.meetings.meeting.not_allowed
  - decidim.meetings.directory.meetings.index.all
  - decidim.meetings.meetings.{create, update}.{invalid, success}
  - decidim.scopes.global
  - decidim.scopes.picker.*
  - decidim.system.organizations.omniauth_settings.{france_connect, france_connect_profile, france_connect_uid}.*
  - decidim.system.organizations.omniauth_settings.publik.*
  - decidim.verifications.authorizations.create.*
  - decidim.verifications.authorizations.first_login.actions.*
  - decidim.proposals.admin.exports.column_name.proposal.*
  - decidim.surveys.admin.exports.column_name.data.*
  - decidim.devise.registrations.new.gender.*
  - decidim.devise.registrations.new.month_name.*
  - activemodel.attributes.participatory_process.announcement
  - activemodel.attributes.participatory_process.*
  - activemodel.attributes.participatory_process_group.*
  - activemodel.attributes.participatory_process_step.*
  - activemodel.attributes.participatory_process_user_role.*
  - activemodel.errors.models.participatory_process.attributes.document.invalid_document_type
  - activemodel.models.decidim/participatory_process_step_activated_event
  - activemodel.models.decidim/participatory_process_step_changed_event
  - activerecord.models.decidim/participatory_process
  - activerecord.models.decidim/participatory_process_group
  - activerecord.models.decidim/participatory_process_step
  - decidim.admin.actions.*
  - decidim.admin.menu.participatory_process_groups
  - decidim.admin.menu.participatory_process_groups_submenu.info
  - decidim.admin.menu.participatory_process_groups_submenu.landing_page
  - decidim.admin.menu.participatory_processes
  - decidim.admin.menu.participatory_processes_submenu.*
  - decidim.admin.models.participatory_process.fields.*
  - decidim.admin.models.participatory_process.name
  - decidim.admin.models.participatory_process_group.fields.title
  - decidim.admin.models.participatory_process_group.name
  - decidim.admin.models.participatory_process_step.fields.*
  - decidim.admin.models.participatory_process_step.name
  - decidim.admin.models.participatory_process_user_role.fields.*
  - decidim.admin.models.participatory_process_user_role.name
  - decidim.admin.models.participatory_process_user_role.roles.*
  - decidim.admin.models.user.fields.invitation_accepted_at
  - decidim.admin.models.user.fields.invitation_sent_at
  - decidim.admin.participatory_process_copies.new.copy
  - decidim.admin.participatory_process_copies.new.select
  - decidim.admin.participatory_process_copies.new.title
  - decidim.admin.participatory_process_group_landing_page.edit.active_content_blocks
  - decidim.admin.participatory_process_group_landing_page.edit.inactive_content_blocks
  - decidim.admin.participatory_process_group_landing_page_content_blocks.edit.update
  - decidim.admin.participatory_process_groups.destroy.error
  - decidim.admin.participatory_process_groups.destroy.success
  - decidim.admin.participatory_process_groups.edit.title
  - decidim.admin.participatory_process_groups.edit.update
  - decidim.admin.participatory_process_groups.new.create
  - decidim.admin.participatory_process_groups.new.title
  - decidim.admin.participatory_process_groups.update.error
  - decidim.admin.participatory_process_groups.update.success
  - decidim.admin.participatory_process_imports.create.error
  - decidim.admin.participatory_process_imports.create.success
  - decidim.admin_log.participatory_process.create
  - decidim.admin_log.participatory_process.publish
  - decidim.admin_log.participatory_process.unpublish
  - decidim.admin_log.participatory_process.update
  - decidim.admin_log.participatory_process_group.create
  - decidim.admin_log.participatory_process_group.update
  - decidim.admin_log.participatory_process_step.*
  - decidim.admin_log.participatory_process_user_role.create
  - decidim.admin_log.participatory_process_user_role.delete
  - decidim.admin_log.participatory_process_user_role.update
  - decidim.events.participatory_process.role_assigned.*
  - decidim.events.participatory_process.step_activated.*
  - decidim.events.participatory_process.step_activated.notification_title
  - decidim.events.participatory_process.step_changed.email_intro
  - decidim.events.participatory_process.step_changed.email_outro
  - decidim.events.participatory_process.step_changed.email_subject
  - decidim.events.participatory_process.step_changed.notification_title
  - decidim.help.participatory_spaces.participatory_processes.contextual
  - decidim.help.participatory_spaces.participatory_processes.page
  - decidim.help.participatory_spaces.participatory_processes.title
  - decidim.meetings.meetings.error
  - decidim.meetings.meetings.new.import
  - decidim.meetings.meetings.new.select
  - decidim.meetings.meetings.new.title
  - decidim.meetings.meetings.success
  - decidim.meetings.participatory_process_publications.*
  - decidim.meetings.participatory_process_step_activations.create.error
  - decidim.meetings.participatory_process_step_activations.create.success
  - decidim.meetings.participatory_process_steps.*
  - decidim.meetings.participatory_process_steps.update.success
  - decidim.meetings.participatory_process_user_roles.create.error
  - decidim.meetings.participatory_process_user_roles.create.success
  - decidim.meetings.participatory_process_user_roles.destroy.success
  - decidim.meetings.participatory_process_user_roles.edit.title
  - decidim.meetings.participatory_process_user_roles.edit.update
  - decidim.meetings.participatory_process_user_roles.index.process_admins_title
  - decidim.meetings.participatory_process_user_roles.new.create
  - decidim.meetings.participatory_process_user_roles.new.title
  - decidim.meetings.participatory_process_user_roles.update.error
  - decidim.meetings.participatory_process_user_roles.update.success
  - decidim.meetings.participatory_processes.create.error
  - decidim.meetings.participatory_processes.create.success
  - decidim.meetings.participatory_processes.edit.update
  - decidim.meetings.participatory_processes.index.not_published
  - decidim.meetings.participatory_processes.index.private
  - decidim.meetings.participatory_processes.index.public
  - decidim.meetings.participatory_processes.index.published
  - decidim.meetings.participatory_processes.new.create
  - decidim.meetings.participatory_processes.new.title
  - decidim.meetings.participatory_processes.update.error
  - decidim.meetings.participatory_processes.update.success
  - decidim.meetings.participatory_processes_copies.create.error
  - decidim.meetings.participatory_processes_copies.create.success
  - decidim.meetings.participatory_processes_group.create.error
  - decidim.meetings.participatory_processes_group.create.success
  - decidim.meetings.titles.participatory_process_groups
  - decidim.meetings.titles.participatory_processes
  - decidim.meetings.users.resend_invitation.error
  - decidim.meetings.users.resend_invitation.success
  - decidim.menu.processes
  - decidim.metrics.participatory_processes.description
  - decidim.metrics.participatory_processes.object
  - decidim.metrics.participatory_processes.title
  - decidim.participatory_process_groups.content_blocks.html_1.name
  - decidim.participatory_process_groups.content_blocks.html_2.name
  - decidim.participatory_process_groups.content_blocks.html_3.name
  - decidim.participatory_process_groups.content_blocks.metadata.developer_group
  - decidim.participatory_process_groups.content_blocks.metadata.name
  - decidim.participatory_process_groups.content_blocks.metadata.participatory_scope
  - decidim.participatory_process_groups.content_blocks.metadata.participatory_structure
  - decidim.participatory_process_groups.content_blocks.metadata.target
  - decidim.participatory_process_groups.content_blocks.participatory_processes.name
  - decidim.participatory_process_groups.content_blocks.stats.name
  - decidim.participatory_process_groups.content_blocks.title.meta_scope
  - decidim.participatory_process_groups.content_blocks.title.name
  - decidim.participatory_process_groups.content_blocks.title.participatory_processes
  - decidim.participatory_process_groups.show.title
  - decidim.participatory_process_steps.index.process_steps
  - decidim.participatory_process_steps.index.title
  - decidim.participatory_processes.admin.content_blocks.highlighted_processes.max_results
  - decidim.participatory_processes.admin.new_import.accepted_types.json
  - decidim.participatory_processes.admin.participatory_process_copies.form.slug_help
  - decidim.participatory_processes.admin.participatory_process_groups.form.*
  - decidim.participatory_processes.admin.participatory_process_imports.form.*
  - decidim.participatory_processes.admin.participatory_process_steps.form.*
  - decidim.participatory_processes.content_blocks.highlighted_processes.name
  - decidim.participatory_processes.index.title
  - decidim.participatory_processes.last_activity.new_participatory_process
  - decidim.participatory_processes.pages.home.highlighted_processes.*
  - decidim.participatory_processes.participatory_process_steps.index.back_to_process
  - decidim.participatory_processes.participatory_processes.filters.*
  - decidim.participatory_processes.participatory_processes.index.loading
  - decidim.participatory_processes.show.belongs_to_group
  - decidim.participatory_processes.show.dates
  - decidim.participatory_processes.show.unspecified
  - decidim.statistics.processes_count
  - layouts.decidim.participatory_process_groups.participatory_process_group.browse
  - layouts.decidim.participatory_process_groups.participatory_process_group.browse_resource
  - layouts.decidim.participatory_process_widgets.show.active_step
  - layouts.decidim.participatory_process_widgets.show.take_part
  - layouts.decidim.participatory_processes.index.promoted_processes
  - layouts.decidim.participatory_processes.participatory_process.active_step
  - layouts.decidim.participatory_processes.participatory_process.*
  - layouts.decidim.participatory_processes.promoted_process_group.more_info
  - layouts.decidim.process_header_steps.step
  - layouts.decidim.process_header_steps.view_steps
  - layouts.decidim.process_navigation.process_menu_item
  - decidim.participatory_process_groups.content_blocks.*
  - decidim.admin.forms.file_help.emitter.*

