# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en

## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
    - app
    - lib

  # Root directories for relative keys resolution.
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/services
    - app/views
    - app/cells

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - "*.jpeg"
    - "*.odt"
    - "*.docx"

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  strict: false

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

translation:
  deepl_api_key: <%= ENV["DEEPL_API_KEY"] %>

# Do not consider these keys missing:
ignore_missing:
 - activemodel.attributes.participatory_process.private_space
 - activemodel.attributes.osp_authorization_handler.*
 - decidim.authorization_handlers.osp_authorization_handler.*
 - decidim.assemblies.admin.assemblies.form.*
 - decidim.assemblies.show.*
 - layouts.decidim.footer.*
 - layouts.decidim.participatory_processes.promoted_process.*
 - decidim.participatory_processes.show.*
 - decidim.participatory_process.show.*
 - decidim.pages.home.sub_hero.*
 - decidim.participatory_processes.admin.participatory_processes.form.address_help
 - decidim.account.show.{change_password,update_account}
 - layouts.decidim.user_menu.profile
 - faker.*
 - decidim.statutory_representative.inform.*
 - .global.age.*
 - decidim.admin.actions.*
 - decidim.admin.titles.*
 - decidim.admin.models.scope_type.fields.*
# Consider these keys used:
ignore_unused:
  - decidim.authorization_handlers.osp_authorization_handler.*
  - decidim.devise.registrations.new.gender.*
  - decidim.devise.registrations.new.month_name.*
  - activemodel.attributes.assembly.sort_children
  - decidim.devise.registrations.new.*
  - devise.mailer.invitation_instructions.*
  - layouts.decidim.footer.*
  - decidim.debates.admin.exports.column_name.debates.*
  - decidim.meetings.admin.exports.column_name.*
  - decidim.comments.exports.column_name.registrations.*
  - decidim.comments.exports.column_name.*
  - decidim.proposals.admin.exports.column_name.proposals.*
  - decidim.forms.user_answers_serializer.*
  - decidim.proposals.admin.exports.*
  - faker.*
  - layouts.decidim.participatory_process_groups.participatory_process_group.processes_count
  - decidim.participatory_processes.emitter.values.*
  - global.age.*
