:concurrency: 5
:queues:
  - mailers
  - default
  - backups
  - events
  - newsletter
  - exports
  - user_report
  - block_user
  - scheduled
  - translations
  - metrics
  - vote_reminder
  - reminders
  - low

:scheduler:
  :schedule:
    CalculateAllMetrics:
      cron: '0 9 0 * * *' # Run at 00:09
      class: CalculateAllMetricsJob
      queue: scheduled
    DetectSpamUsers:
      cron: '0 <%= Random.rand(0..59) %> <%= Random.rand(6..8) %> * * *' # Run randomly between 06:00 and 08:59
      class: Decidim::SpamDetection::MarkUsersJob
      queue: scheduled
    Backup:
      cron: '0 0 4 * * *' # Run at 04:00
      class: BackupJob
      queue: backups
    CleanAdminLogs:
      cron: "0 9 0 * * *"
      class: Decidim::Cleaner::CleanAdminLogsJob
      queue: mailers
    CleanInactiveUsers:
      cron: "0 9 0 * * *"
      class: Decidim::Cleaner::CleanInactiveUsersJob
      queue: mailers
