:concurrency: 5
:queues:
  - default
  - backups
  - metrics
  - mailers
  - newsletter
  - events
  - exports
  - user_report
  - block_user
  - scheduled
  - low

:scheduler:
  :schedule:
    CleanAdminLogs:
      cron: "0 9 0 * * *"
      class: Decidim::Cleaner::CleanAdminLogsJob
      queue: scheduled
    CleanInactiveUsers:
      cron: "0 9 0 * * *"
      class: Decidim::Cleaner::CleanInactiveUsersJob
      queue: scheduled
    CalculateAllMetrics:
      cron: '0 0 0 * * *' # Run at midnight
      class: CalculateAllMetricsJob
      queue: scheduled
    PreloadOpenData:
      cron: '0 1 * * *' # Run at 01:00
      class: PreloadOpenDataJob
      queue: scheduled
    Backup:
      cron: '0 0 4 * * *' # Run at 04:00
      class: BackupJob
      queue: backups
