test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

scaleway:
  service: S3
  endpoint: https://<%= Rails.application.secrets.dig(:scaleway, :endpoint) %>
  access_key_id: <%= Rails.application.secrets.dig(:scaleway, :id) %>
  secret_access_key: <%= Rails.application.secrets.dig(:scaleway, :token) %>
  region: fr-par
  bucket: <%= Rails.application.secrets.dig(:scaleway, :bucket_name) %>
